// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: region/v1/region.proto

package regionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegionService_SearchPoint_FullMethodName           = "/region.v1.RegionService/SearchPoint"
	RegionService_SearchBox_FullMethodName             = "/region.v1.RegionService/SearchBox"
	RegionService_SearchRadius_FullMethodName          = "/region.v1.RegionService/SearchRadius"
	RegionService_FindCrossingLocations_FullMethodName = "/region.v1.RegionService/FindCrossingLocations"
	RegionService_FindRegionPath_FullMethodName        = "/region.v1.RegionService/FindRegionPath"
)

// RegionServiceClient is the client API for RegionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegionServiceClient interface {
	SearchPoint(ctx context.Context, in *SearchPointRequest, opts ...grpc.CallOption) (*SearchPointResponse, error)
	SearchBox(ctx context.Context, in *SearchBoxRequest, opts ...grpc.CallOption) (*SearchBoxResponse, error)
	SearchRadius(ctx context.Context, in *SearchRadiusRequest, opts ...grpc.CallOption) (*SearchRadiusResponse, error)
	FindCrossingLocations(ctx context.Context, in *FindCrossingLocationsRequest, opts ...grpc.CallOption) (*FindCrossingLocationsResponse, error)
	FindRegionPath(ctx context.Context, in *FindRegionPathRequest, opts ...grpc.CallOption) (*FindRegionPathResponse, error)
}

type regionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegionServiceClient(cc grpc.ClientConnInterface) RegionServiceClient {
	return &regionServiceClient{cc}
}

func (c *regionServiceClient) SearchPoint(ctx context.Context, in *SearchPointRequest, opts ...grpc.CallOption) (*SearchPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPointResponse)
	err := c.cc.Invoke(ctx, RegionService_SearchPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) SearchBox(ctx context.Context, in *SearchBoxRequest, opts ...grpc.CallOption) (*SearchBoxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchBoxResponse)
	err := c.cc.Invoke(ctx, RegionService_SearchBox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) SearchRadius(ctx context.Context, in *SearchRadiusRequest, opts ...grpc.CallOption) (*SearchRadiusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchRadiusResponse)
	err := c.cc.Invoke(ctx, RegionService_SearchRadius_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) FindCrossingLocations(ctx context.Context, in *FindCrossingLocationsRequest, opts ...grpc.CallOption) (*FindCrossingLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindCrossingLocationsResponse)
	err := c.cc.Invoke(ctx, RegionService_FindCrossingLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) FindRegionPath(ctx context.Context, in *FindRegionPathRequest, opts ...grpc.CallOption) (*FindRegionPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRegionPathResponse)
	err := c.cc.Invoke(ctx, RegionService_FindRegionPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegionServiceServer is the server API for RegionService service.
// All implementations must embed UnimplementedRegionServiceServer
// for forward compatibility.
type RegionServiceServer interface {
	SearchPoint(context.Context, *SearchPointRequest) (*SearchPointResponse, error)
	SearchBox(context.Context, *SearchBoxRequest) (*SearchBoxResponse, error)
	SearchRadius(context.Context, *SearchRadiusRequest) (*SearchRadiusResponse, error)
	FindCrossingLocations(context.Context, *FindCrossingLocationsRequest) (*FindCrossingLocationsResponse, error)
	FindRegionPath(context.Context, *FindRegionPathRequest) (*FindRegionPathResponse, error)
	mustEmbedUnimplementedRegionServiceServer()
}

// UnimplementedRegionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegionServiceServer struct{}

func (UnimplementedRegionServiceServer) SearchPoint(context.Context, *SearchPointRequest) (*SearchPointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchPoint not implemented")
}
func (UnimplementedRegionServiceServer) SearchBox(context.Context, *SearchBoxRequest) (*SearchBoxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchBox not implemented")
}
func (UnimplementedRegionServiceServer) SearchRadius(context.Context, *SearchRadiusRequest) (*SearchRadiusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchRadius not implemented")
}
func (UnimplementedRegionServiceServer) FindCrossingLocations(context.Context, *FindCrossingLocationsRequest) (*FindCrossingLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindCrossingLocations not implemented")
}
func (UnimplementedRegionServiceServer) FindRegionPath(context.Context, *FindRegionPathRequest) (*FindRegionPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindRegionPath not implemented")
}
func (UnimplementedRegionServiceServer) mustEmbedUnimplementedRegionServiceServer() {}
func (UnimplementedRegionServiceServer) testEmbeddedByValue()                       {}

// UnsafeRegionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegionServiceServer will
// result in compilation errors.
type UnsafeRegionServiceServer interface {
	mustEmbedUnimplementedRegionServiceServer()
}

func RegisterRegionServiceServer(s grpc.ServiceRegistrar, srv RegionServiceServer) {
	// If the following call panics, it indicates UnimplementedRegionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegionService_ServiceDesc, srv)
}

func _RegionService_SearchPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).SearchPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_SearchPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).SearchPoint(ctx, req.(*SearchPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_SearchBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).SearchBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_SearchBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).SearchBox(ctx, req.(*SearchBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_SearchRadius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRadiusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).SearchRadius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_SearchRadius_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).SearchRadius(ctx, req.(*SearchRadiusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_FindCrossingLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCrossingLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).FindCrossingLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_FindCrossingLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).FindCrossingLocations(ctx, req.(*FindCrossingLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_FindRegionPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRegionPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).FindRegionPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_FindRegionPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).FindRegionPath(ctx, req.(*FindRegionPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegionService_ServiceDesc is the grpc.ServiceDesc for RegionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "region.v1.RegionService",
	HandlerType: (*RegionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchPoint",
			Handler:    _RegionService_SearchPoint_Handler,
		},
		{
			MethodName: "SearchBox",
			Handler:    _RegionService_SearchBox_Handler,
		},
		{
			MethodName: "SearchRadius",
			Handler:    _RegionService_SearchRadius_Handler,
		},
		{
			MethodName: "FindCrossingLocations",
			Handler:    _RegionService_FindCrossingLocations_Handler,
		},
		{
			MethodName: "FindRegionPath",
			Handler:    _RegionService_FindRegionPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "region/v1/region.proto",
}
