// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: region/v1/region.proto

package regionv1

import (
	geo "github.com/swayrider/protos/common_types/geo"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoadType int32

const (
	RoadType_MOTORWAY  RoadType = 0
	RoadType_TRUNK     RoadType = 1
	RoadType_PRIMARY   RoadType = 2
	RoadType_SECONDARY RoadType = 3
)

// Enum value maps for RoadType.
var (
	RoadType_name = map[int32]string{
		0: "MOTORWAY",
		1: "TRUNK",
		2: "PRIMARY",
		3: "SECONDARY",
	}
	RoadType_value = map[string]int32{
		"MOTORWAY":  0,
		"TRUNK":     1,
		"PRIMARY":   2,
		"SECONDARY": 3,
	}
)

func (x RoadType) Enum() *RoadType {
	p := new(RoadType)
	*p = x
	return p
}

func (x RoadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoadType) Descriptor() protoreflect.EnumDescriptor {
	return file_region_v1_region_proto_enumTypes[0].Descriptor()
}

func (RoadType) Type() protoreflect.EnumType {
	return &file_region_v1_region_proto_enumTypes[0]
}

func (x RoadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoadType.Descriptor instead.
func (RoadType) EnumDescriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{0}
}

type BorderCrossing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromRegion    string                 `protobuf:"bytes,1,opt,name=from_region,json=fromRegion,proto3" json:"from_region,omitempty"`
	ToRegion      string                 `protobuf:"bytes,2,opt,name=to_region,json=toRegion,proto3" json:"to_region,omitempty"`
	RoadType      RoadType               `protobuf:"varint,3,opt,name=road_type,json=roadType,proto3,enum=region.v1.RoadType" json:"road_type,omitempty"`
	Location      *geo.Coordinate        `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	OsmId         int64                  `protobuf:"varint,5,opt,name=osm_id,json=osmId,proto3" json:"osm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorderCrossing) Reset() {
	*x = BorderCrossing{}
	mi := &file_region_v1_region_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorderCrossing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorderCrossing) ProtoMessage() {}

func (x *BorderCrossing) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorderCrossing.ProtoReflect.Descriptor instead.
func (*BorderCrossing) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{0}
}

func (x *BorderCrossing) GetFromRegion() string {
	if x != nil {
		return x.FromRegion
	}
	return ""
}

func (x *BorderCrossing) GetToRegion() string {
	if x != nil {
		return x.ToRegion
	}
	return ""
}

func (x *BorderCrossing) GetRoadType() RoadType {
	if x != nil {
		return x.RoadType
	}
	return RoadType_MOTORWAY
}

func (x *BorderCrossing) GetLocation() *geo.Coordinate {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *BorderCrossing) GetOsmId() int64 {
	if x != nil {
		return x.OsmId
	}
	return 0
}

type BorderCrossingSimpleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadTypeOrder []RoadType             `protobuf:"varint,1,rep,packed,name=road_type_order,json=roadTypeOrder,proto3,enum=region.v1.RoadType" json:"road_type_order,omitempty"`
	// The road_type_delta defines the distance in meters between different
	// road types for which they are regarded as equally distant from the
	// line string for finding crossings.
	// This means that all roads within this distance are sorted based on the
	// provided road type order
	// If 0 we use 10000 meters
	RoadTypeDelta float64 `protobuf:"fixed64,2,opt,name=road_type_delta,json=roadTypeDelta,proto3" json:"road_type_delta,omitempty"`
	// The drop distance defines the distance in meters between different
	// road types for which a crossing of a road_type lower in the order will
	// be discarded.
	// Typically you would set this to 0.1 times the road_type delta.
	// If not set, this will default to 0.1 times the road_type_delta.
	DropDistance  float64 `protobuf:"fixed64,3,opt,name=drop_distance,json=dropDistance,proto3" json:"drop_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorderCrossingSimpleConfig) Reset() {
	*x = BorderCrossingSimpleConfig{}
	mi := &file_region_v1_region_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorderCrossingSimpleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorderCrossingSimpleConfig) ProtoMessage() {}

func (x *BorderCrossingSimpleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorderCrossingSimpleConfig.ProtoReflect.Descriptor instead.
func (*BorderCrossingSimpleConfig) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{1}
}

func (x *BorderCrossingSimpleConfig) GetRoadTypeOrder() []RoadType {
	if x != nil {
		return x.RoadTypeOrder
	}
	return nil
}

func (x *BorderCrossingSimpleConfig) GetRoadTypeDelta() float64 {
	if x != nil {
		return x.RoadTypeDelta
	}
	return 0
}

func (x *BorderCrossingSimpleConfig) GetDropDistance() float64 {
	if x != nil {
		return x.DropDistance
	}
	return 0
}

type BorderCrossingDefinition struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxBorderDistance float64                `protobuf:"fixed64,1,opt,name=max_border_distance,json=maxBorderDistance,proto3" json:"max_border_distance,omitempty"` // If 0 This is the fallback (furtherst away); This value is in meters
	RoadTypeOrder     []RoadType             `protobuf:"varint,2,rep,packed,name=road_type_order,json=roadTypeOrder,proto3,enum=region.v1.RoadType" json:"road_type_order,omitempty"`
	// The road_type_delta defines the distance in meters between different
	// road types for which they are regarded as equally distant from the
	// line string for finding crossings.
	// This means that all roads within this distance are sorted based on the
	// provided road type order
	// If 0 we use the actual border distance
	RoadTypeDelta float64 `protobuf:"fixed64,3,opt,name=road_type_delta,json=roadTypeDelta,proto3" json:"road_type_delta,omitempty"`
	// The drop distance defines the distance in meters between different
	// road types for which a crossing of a road_type lower in the order will
	// be discarded.
	// Typically you would set this to 0.1 times the road_type delta.
	// If not set, this will default to 0.1 times the road_type_delta.
	DropDistance  float64 `protobuf:"fixed64,4,opt,name=drop_distance,json=dropDistance,proto3" json:"drop_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorderCrossingDefinition) Reset() {
	*x = BorderCrossingDefinition{}
	mi := &file_region_v1_region_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorderCrossingDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorderCrossingDefinition) ProtoMessage() {}

func (x *BorderCrossingDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorderCrossingDefinition.ProtoReflect.Descriptor instead.
func (*BorderCrossingDefinition) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{2}
}

func (x *BorderCrossingDefinition) GetMaxBorderDistance() float64 {
	if x != nil {
		return x.MaxBorderDistance
	}
	return 0
}

func (x *BorderCrossingDefinition) GetRoadTypeOrder() []RoadType {
	if x != nil {
		return x.RoadTypeOrder
	}
	return nil
}

func (x *BorderCrossingDefinition) GetRoadTypeDelta() float64 {
	if x != nil {
		return x.RoadTypeDelta
	}
	return 0
}

func (x *BorderCrossingDefinition) GetDropDistance() float64 {
	if x != nil {
		return x.DropDistance
	}
	return 0
}

type BorderCrossingAdvancedConfig struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Definitions   []*BorderCrossingDefinition `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorderCrossingAdvancedConfig) Reset() {
	*x = BorderCrossingAdvancedConfig{}
	mi := &file_region_v1_region_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorderCrossingAdvancedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorderCrossingAdvancedConfig) ProtoMessage() {}

func (x *BorderCrossingAdvancedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorderCrossingAdvancedConfig.ProtoReflect.Descriptor instead.
func (*BorderCrossingAdvancedConfig) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{3}
}

func (x *BorderCrossingAdvancedConfig) GetDefinitions() []*BorderCrossingDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

type SearchPointRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Location        *geo.Coordinate        `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	IncludeExtended bool                   `protobuf:"varint,2,opt,name=include_extended,json=includeExtended,proto3" json:"include_extended,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchPointRequest) Reset() {
	*x = SearchPointRequest{}
	mi := &file_region_v1_region_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPointRequest) ProtoMessage() {}

func (x *SearchPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPointRequest.ProtoReflect.Descriptor instead.
func (*SearchPointRequest) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{4}
}

func (x *SearchPointRequest) GetLocation() *geo.Coordinate {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *SearchPointRequest) GetIncludeExtended() bool {
	if x != nil {
		return x.IncludeExtended
	}
	return false
}

type SearchPointResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CoreRegions     []string               `protobuf:"bytes,1,rep,name=core_regions,json=coreRegions,proto3" json:"core_regions,omitempty"`
	ExtendedRegions []string               `protobuf:"bytes,2,rep,name=extended_regions,json=extendedRegions,proto3" json:"extended_regions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchPointResponse) Reset() {
	*x = SearchPointResponse{}
	mi := &file_region_v1_region_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPointResponse) ProtoMessage() {}

func (x *SearchPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPointResponse.ProtoReflect.Descriptor instead.
func (*SearchPointResponse) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{5}
}

func (x *SearchPointResponse) GetCoreRegions() []string {
	if x != nil {
		return x.CoreRegions
	}
	return nil
}

func (x *SearchPointResponse) GetExtendedRegions() []string {
	if x != nil {
		return x.ExtendedRegions
	}
	return nil
}

type SearchBoxRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Box             *geo.BoundingBox       `protobuf:"bytes,1,opt,name=box,proto3" json:"box,omitempty"`
	IncludeExtended bool                   `protobuf:"varint,2,opt,name=include_extended,json=includeExtended,proto3" json:"include_extended,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchBoxRequest) Reset() {
	*x = SearchBoxRequest{}
	mi := &file_region_v1_region_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBoxRequest) ProtoMessage() {}

func (x *SearchBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBoxRequest.ProtoReflect.Descriptor instead.
func (*SearchBoxRequest) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{6}
}

func (x *SearchBoxRequest) GetBox() *geo.BoundingBox {
	if x != nil {
		return x.Box
	}
	return nil
}

func (x *SearchBoxRequest) GetIncludeExtended() bool {
	if x != nil {
		return x.IncludeExtended
	}
	return false
}

type SearchBoxResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CoreRegions     []string               `protobuf:"bytes,1,rep,name=core_regions,json=coreRegions,proto3" json:"core_regions,omitempty"`
	ExtendedRegions []string               `protobuf:"bytes,2,rep,name=extended_regions,json=extendedRegions,proto3" json:"extended_regions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchBoxResponse) Reset() {
	*x = SearchBoxResponse{}
	mi := &file_region_v1_region_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBoxResponse) ProtoMessage() {}

func (x *SearchBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBoxResponse.ProtoReflect.Descriptor instead.
func (*SearchBoxResponse) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{7}
}

func (x *SearchBoxResponse) GetCoreRegions() []string {
	if x != nil {
		return x.CoreRegions
	}
	return nil
}

func (x *SearchBoxResponse) GetExtendedRegions() []string {
	if x != nil {
		return x.ExtendedRegions
	}
	return nil
}

type SearchRadiusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Location        *geo.Coordinate        `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	RadiusKm        float64                `protobuf:"fixed64,2,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	IncludeExtended bool                   `protobuf:"varint,3,opt,name=include_extended,json=includeExtended,proto3" json:"include_extended,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchRadiusRequest) Reset() {
	*x = SearchRadiusRequest{}
	mi := &file_region_v1_region_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRadiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRadiusRequest) ProtoMessage() {}

func (x *SearchRadiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRadiusRequest.ProtoReflect.Descriptor instead.
func (*SearchRadiusRequest) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{8}
}

func (x *SearchRadiusRequest) GetLocation() *geo.Coordinate {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *SearchRadiusRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *SearchRadiusRequest) GetIncludeExtended() bool {
	if x != nil {
		return x.IncludeExtended
	}
	return false
}

type SearchRadiusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CoreRegions     []string               `protobuf:"bytes,1,rep,name=core_regions,json=coreRegions,proto3" json:"core_regions,omitempty"`
	ExtendedRegions []string               `protobuf:"bytes,2,rep,name=extended_regions,json=extendedRegions,proto3" json:"extended_regions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchRadiusResponse) Reset() {
	*x = SearchRadiusResponse{}
	mi := &file_region_v1_region_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRadiusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRadiusResponse) ProtoMessage() {}

func (x *SearchRadiusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRadiusResponse.ProtoReflect.Descriptor instead.
func (*SearchRadiusResponse) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{9}
}

func (x *SearchRadiusResponse) GetCoreRegions() []string {
	if x != nil {
		return x.CoreRegions
	}
	return nil
}

func (x *SearchRadiusResponse) GetExtendedRegions() []string {
	if x != nil {
		return x.ExtendedRegions
	}
	return nil
}

type FindCrossingLocationsRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	FromRegion   string                 `protobuf:"bytes,1,opt,name=from_region,json=fromRegion,proto3" json:"from_region,omitempty"`
	ToRegion     string                 `protobuf:"bytes,2,opt,name=to_region,json=toRegion,proto3" json:"to_region,omitempty"`
	FromLocation *geo.Coordinate        `protobuf:"bytes,3,opt,name=from_location,json=fromLocation,proto3" json:"from_location,omitempty"`
	ToLocation   *geo.Coordinate        `protobuf:"bytes,4,opt,name=to_location,json=toLocation,proto3" json:"to_location,omitempty"`
	// repeated RoadType road_type_order = 5;          // Default order is MOTORWAY, TRUNK, PRIMARY, SECONDARY
	// int32 limit = 6;                                // Default = 3
	// double road_type_delta = 7;                    // Default = 10Km
	//
	// Types that are valid to be assigned to ConfigOneof:
	//
	//	*FindCrossingLocationsRequest_SimpleConfig
	//	*FindCrossingLocationsRequest_AdvancedConfig
	ConfigOneof   isFindCrossingLocationsRequest_ConfigOneof `protobuf_oneof:"config_oneof"`
	Limit         int32                                      `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCrossingLocationsRequest) Reset() {
	*x = FindCrossingLocationsRequest{}
	mi := &file_region_v1_region_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCrossingLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCrossingLocationsRequest) ProtoMessage() {}

func (x *FindCrossingLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCrossingLocationsRequest.ProtoReflect.Descriptor instead.
func (*FindCrossingLocationsRequest) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{10}
}

func (x *FindCrossingLocationsRequest) GetFromRegion() string {
	if x != nil {
		return x.FromRegion
	}
	return ""
}

func (x *FindCrossingLocationsRequest) GetToRegion() string {
	if x != nil {
		return x.ToRegion
	}
	return ""
}

func (x *FindCrossingLocationsRequest) GetFromLocation() *geo.Coordinate {
	if x != nil {
		return x.FromLocation
	}
	return nil
}

func (x *FindCrossingLocationsRequest) GetToLocation() *geo.Coordinate {
	if x != nil {
		return x.ToLocation
	}
	return nil
}

func (x *FindCrossingLocationsRequest) GetConfigOneof() isFindCrossingLocationsRequest_ConfigOneof {
	if x != nil {
		return x.ConfigOneof
	}
	return nil
}

func (x *FindCrossingLocationsRequest) GetSimpleConfig() *BorderCrossingSimpleConfig {
	if x != nil {
		if x, ok := x.ConfigOneof.(*FindCrossingLocationsRequest_SimpleConfig); ok {
			return x.SimpleConfig
		}
	}
	return nil
}

func (x *FindCrossingLocationsRequest) GetAdvancedConfig() *BorderCrossingAdvancedConfig {
	if x != nil {
		if x, ok := x.ConfigOneof.(*FindCrossingLocationsRequest_AdvancedConfig); ok {
			return x.AdvancedConfig
		}
	}
	return nil
}

func (x *FindCrossingLocationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type isFindCrossingLocationsRequest_ConfigOneof interface {
	isFindCrossingLocationsRequest_ConfigOneof()
}

type FindCrossingLocationsRequest_SimpleConfig struct {
	SimpleConfig *BorderCrossingSimpleConfig `protobuf:"bytes,5,opt,name=simple_config,json=simpleConfig,proto3,oneof"`
}

type FindCrossingLocationsRequest_AdvancedConfig struct {
	AdvancedConfig *BorderCrossingAdvancedConfig `protobuf:"bytes,6,opt,name=advanced_config,json=advancedConfig,proto3,oneof"`
}

func (*FindCrossingLocationsRequest_SimpleConfig) isFindCrossingLocationsRequest_ConfigOneof() {}

func (*FindCrossingLocationsRequest_AdvancedConfig) isFindCrossingLocationsRequest_ConfigOneof() {}

type FindCrossingLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crossings     []*BorderCrossing      `protobuf:"bytes,1,rep,name=crossings,proto3" json:"crossings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCrossingLocationsResponse) Reset() {
	*x = FindCrossingLocationsResponse{}
	mi := &file_region_v1_region_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCrossingLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCrossingLocationsResponse) ProtoMessage() {}

func (x *FindCrossingLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCrossingLocationsResponse.ProtoReflect.Descriptor instead.
func (*FindCrossingLocationsResponse) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{11}
}

func (x *FindCrossingLocationsResponse) GetCrossings() []*BorderCrossing {
	if x != nil {
		return x.Crossings
	}
	return nil
}

type FindRegionPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromRegion    string                 `protobuf:"bytes,1,opt,name=from_region,json=fromRegion,proto3" json:"from_region,omitempty"`
	ToRegion      string                 `protobuf:"bytes,2,opt,name=to_region,json=toRegion,proto3" json:"to_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRegionPathRequest) Reset() {
	*x = FindRegionPathRequest{}
	mi := &file_region_v1_region_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRegionPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRegionPathRequest) ProtoMessage() {}

func (x *FindRegionPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRegionPathRequest.ProtoReflect.Descriptor instead.
func (*FindRegionPathRequest) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{12}
}

func (x *FindRegionPathRequest) GetFromRegion() string {
	if x != nil {
		return x.FromRegion
	}
	return ""
}

func (x *FindRegionPathRequest) GetToRegion() string {
	if x != nil {
		return x.ToRegion
	}
	return ""
}

type FindRegionPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRegionPathResponse) Reset() {
	*x = FindRegionPathResponse{}
	mi := &file_region_v1_region_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRegionPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRegionPathResponse) ProtoMessage() {}

func (x *FindRegionPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_region_v1_region_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRegionPathResponse.ProtoReflect.Descriptor instead.
func (*FindRegionPathResponse) Descriptor() ([]byte, []int) {
	return file_region_v1_region_proto_rawDescGZIP(), []int{13}
}

func (x *FindRegionPathResponse) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

var File_region_v1_region_proto protoreflect.FileDescriptor

const file_region_v1_region_proto_rawDesc = "" +
	"\n" +
	"\x16region/v1/region.proto\x12\tregion.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1acommon_types/geo/geo.proto\"\xcd\x01\n" +
	"\x0eBorderCrossing\x12\x1f\n" +
	"\vfrom_region\x18\x01 \x01(\tR\n" +
	"fromRegion\x12\x1b\n" +
	"\tto_region\x18\x02 \x01(\tR\btoRegion\x120\n" +
	"\troad_type\x18\x03 \x01(\x0e2\x13.region.v1.RoadTypeR\broadType\x124\n" +
	"\blocation\x18\x04 \x01(\v2\x18.common_types.CoordinateR\blocation\x12\x15\n" +
	"\x06osm_id\x18\x05 \x01(\x03R\x05osmId\"\xa6\x01\n" +
	"\x1aBorderCrossingSimpleConfig\x12;\n" +
	"\x0froad_type_order\x18\x01 \x03(\x0e2\x13.region.v1.RoadTypeR\rroadTypeOrder\x12&\n" +
	"\x0froad_type_delta\x18\x02 \x01(\x01R\rroadTypeDelta\x12#\n" +
	"\rdrop_distance\x18\x03 \x01(\x01R\fdropDistance\"\xd4\x01\n" +
	"\x18BorderCrossingDefinition\x12.\n" +
	"\x13max_border_distance\x18\x01 \x01(\x01R\x11maxBorderDistance\x12;\n" +
	"\x0froad_type_order\x18\x02 \x03(\x0e2\x13.region.v1.RoadTypeR\rroadTypeOrder\x12&\n" +
	"\x0froad_type_delta\x18\x03 \x01(\x01R\rroadTypeDelta\x12#\n" +
	"\rdrop_distance\x18\x04 \x01(\x01R\fdropDistance\"e\n" +
	"\x1cBorderCrossingAdvancedConfig\x12E\n" +
	"\vdefinitions\x18\x01 \x03(\v2#.region.v1.BorderCrossingDefinitionR\vdefinitions\"u\n" +
	"\x12SearchPointRequest\x124\n" +
	"\blocation\x18\x01 \x01(\v2\x18.common_types.CoordinateR\blocation\x12)\n" +
	"\x10include_extended\x18\x02 \x01(\bR\x0fincludeExtended\"c\n" +
	"\x13SearchPointResponse\x12!\n" +
	"\fcore_regions\x18\x01 \x03(\tR\vcoreRegions\x12)\n" +
	"\x10extended_regions\x18\x02 \x03(\tR\x0fextendedRegions\"j\n" +
	"\x10SearchBoxRequest\x12+\n" +
	"\x03box\x18\x01 \x01(\v2\x19.common_types.BoundingBoxR\x03box\x12)\n" +
	"\x10include_extended\x18\x02 \x01(\bR\x0fincludeExtended\"a\n" +
	"\x11SearchBoxResponse\x12!\n" +
	"\fcore_regions\x18\x01 \x03(\tR\vcoreRegions\x12)\n" +
	"\x10extended_regions\x18\x02 \x03(\tR\x0fextendedRegions\"\x93\x01\n" +
	"\x13SearchRadiusRequest\x124\n" +
	"\blocation\x18\x01 \x01(\v2\x18.common_types.CoordinateR\blocation\x12\x1b\n" +
	"\tradius_km\x18\x02 \x01(\x01R\bradiusKm\x12)\n" +
	"\x10include_extended\x18\x03 \x01(\bR\x0fincludeExtended\"d\n" +
	"\x14SearchRadiusResponse\x12!\n" +
	"\fcore_regions\x18\x01 \x03(\tR\vcoreRegions\x12)\n" +
	"\x10extended_regions\x18\x02 \x03(\tR\x0fextendedRegions\"\x9e\x03\n" +
	"\x1cFindCrossingLocationsRequest\x12\x1f\n" +
	"\vfrom_region\x18\x01 \x01(\tR\n" +
	"fromRegion\x12\x1b\n" +
	"\tto_region\x18\x02 \x01(\tR\btoRegion\x12=\n" +
	"\rfrom_location\x18\x03 \x01(\v2\x18.common_types.CoordinateR\ffromLocation\x129\n" +
	"\vto_location\x18\x04 \x01(\v2\x18.common_types.CoordinateR\n" +
	"toLocation\x12L\n" +
	"\rsimple_config\x18\x05 \x01(\v2%.region.v1.BorderCrossingSimpleConfigH\x00R\fsimpleConfig\x12R\n" +
	"\x0fadvanced_config\x18\x06 \x01(\v2'.region.v1.BorderCrossingAdvancedConfigH\x00R\x0eadvancedConfig\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limitB\x0e\n" +
	"\fconfig_oneof\"X\n" +
	"\x1dFindCrossingLocationsResponse\x127\n" +
	"\tcrossings\x18\x01 \x03(\v2\x19.region.v1.BorderCrossingR\tcrossings\"U\n" +
	"\x15FindRegionPathRequest\x12\x1f\n" +
	"\vfrom_region\x18\x01 \x01(\tR\n" +
	"fromRegion\x12\x1b\n" +
	"\tto_region\x18\x02 \x01(\tR\btoRegion\",\n" +
	"\x16FindRegionPathResponse\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04path*?\n" +
	"\bRoadType\x12\f\n" +
	"\bMOTORWAY\x10\x00\x12\t\n" +
	"\x05TRUNK\x10\x01\x12\v\n" +
	"\aPRIMARY\x10\x02\x12\r\n" +
	"\tSECONDARY\x10\x032\x91\x05\n" +
	"\rRegionService\x12t\n" +
	"\vSearchPoint\x12\x1d.region.v1.SearchPointRequest\x1a\x1e.region.v1.SearchPointResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/region/search-point\x12l\n" +
	"\tSearchBox\x12\x1b.region.v1.SearchBoxRequest\x1a\x1c.region.v1.SearchBoxResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/region/search-box\x12x\n" +
	"\fSearchRadius\x12\x1e.region.v1.SearchRadiusRequest\x1a\x1f.region.v1.SearchRadiusResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/region/search-radius\x12\x9d\x01\n" +
	"\x15FindCrossingLocations\x12'.region.v1.FindCrossingLocationsRequest\x1a(.region.v1.FindCrossingLocationsResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/region/find-crossing-locations\x12\x81\x01\n" +
	"\x0eFindRegionPath\x12 .region.v1.FindRegionPathRequest\x1a!.region.v1.FindRegionPathResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/region/find-region-pathB0Z.github.com/swayrider/protos/region/v1;regionv1b\x06proto3"

var (
	file_region_v1_region_proto_rawDescOnce sync.Once
	file_region_v1_region_proto_rawDescData []byte
)

func file_region_v1_region_proto_rawDescGZIP() []byte {
	file_region_v1_region_proto_rawDescOnce.Do(func() {
		file_region_v1_region_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_region_v1_region_proto_rawDesc), len(file_region_v1_region_proto_rawDesc)))
	})
	return file_region_v1_region_proto_rawDescData
}

var file_region_v1_region_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_region_v1_region_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_region_v1_region_proto_goTypes = []any{
	(RoadType)(0),                         // 0: region.v1.RoadType
	(*BorderCrossing)(nil),                // 1: region.v1.BorderCrossing
	(*BorderCrossingSimpleConfig)(nil),    // 2: region.v1.BorderCrossingSimpleConfig
	(*BorderCrossingDefinition)(nil),      // 3: region.v1.BorderCrossingDefinition
	(*BorderCrossingAdvancedConfig)(nil),  // 4: region.v1.BorderCrossingAdvancedConfig
	(*SearchPointRequest)(nil),            // 5: region.v1.SearchPointRequest
	(*SearchPointResponse)(nil),           // 6: region.v1.SearchPointResponse
	(*SearchBoxRequest)(nil),              // 7: region.v1.SearchBoxRequest
	(*SearchBoxResponse)(nil),             // 8: region.v1.SearchBoxResponse
	(*SearchRadiusRequest)(nil),           // 9: region.v1.SearchRadiusRequest
	(*SearchRadiusResponse)(nil),          // 10: region.v1.SearchRadiusResponse
	(*FindCrossingLocationsRequest)(nil),  // 11: region.v1.FindCrossingLocationsRequest
	(*FindCrossingLocationsResponse)(nil), // 12: region.v1.FindCrossingLocationsResponse
	(*FindRegionPathRequest)(nil),         // 13: region.v1.FindRegionPathRequest
	(*FindRegionPathResponse)(nil),        // 14: region.v1.FindRegionPathResponse
	(*geo.Coordinate)(nil),                // 15: common_types.Coordinate
	(*geo.BoundingBox)(nil),               // 16: common_types.BoundingBox
}
var file_region_v1_region_proto_depIdxs = []int32{
	0,  // 0: region.v1.BorderCrossing.road_type:type_name -> region.v1.RoadType
	15, // 1: region.v1.BorderCrossing.location:type_name -> common_types.Coordinate
	0,  // 2: region.v1.BorderCrossingSimpleConfig.road_type_order:type_name -> region.v1.RoadType
	0,  // 3: region.v1.BorderCrossingDefinition.road_type_order:type_name -> region.v1.RoadType
	3,  // 4: region.v1.BorderCrossingAdvancedConfig.definitions:type_name -> region.v1.BorderCrossingDefinition
	15, // 5: region.v1.SearchPointRequest.location:type_name -> common_types.Coordinate
	16, // 6: region.v1.SearchBoxRequest.box:type_name -> common_types.BoundingBox
	15, // 7: region.v1.SearchRadiusRequest.location:type_name -> common_types.Coordinate
	15, // 8: region.v1.FindCrossingLocationsRequest.from_location:type_name -> common_types.Coordinate
	15, // 9: region.v1.FindCrossingLocationsRequest.to_location:type_name -> common_types.Coordinate
	2,  // 10: region.v1.FindCrossingLocationsRequest.simple_config:type_name -> region.v1.BorderCrossingSimpleConfig
	4,  // 11: region.v1.FindCrossingLocationsRequest.advanced_config:type_name -> region.v1.BorderCrossingAdvancedConfig
	1,  // 12: region.v1.FindCrossingLocationsResponse.crossings:type_name -> region.v1.BorderCrossing
	5,  // 13: region.v1.RegionService.SearchPoint:input_type -> region.v1.SearchPointRequest
	7,  // 14: region.v1.RegionService.SearchBox:input_type -> region.v1.SearchBoxRequest
	9,  // 15: region.v1.RegionService.SearchRadius:input_type -> region.v1.SearchRadiusRequest
	11, // 16: region.v1.RegionService.FindCrossingLocations:input_type -> region.v1.FindCrossingLocationsRequest
	13, // 17: region.v1.RegionService.FindRegionPath:input_type -> region.v1.FindRegionPathRequest
	6,  // 18: region.v1.RegionService.SearchPoint:output_type -> region.v1.SearchPointResponse
	8,  // 19: region.v1.RegionService.SearchBox:output_type -> region.v1.SearchBoxResponse
	10, // 20: region.v1.RegionService.SearchRadius:output_type -> region.v1.SearchRadiusResponse
	12, // 21: region.v1.RegionService.FindCrossingLocations:output_type -> region.v1.FindCrossingLocationsResponse
	14, // 22: region.v1.RegionService.FindRegionPath:output_type -> region.v1.FindRegionPathResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_region_v1_region_proto_init() }
func file_region_v1_region_proto_init() {
	if File_region_v1_region_proto != nil {
		return
	}
	file_region_v1_region_proto_msgTypes[10].OneofWrappers = []any{
		(*FindCrossingLocationsRequest_SimpleConfig)(nil),
		(*FindCrossingLocationsRequest_AdvancedConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_region_v1_region_proto_rawDesc), len(file_region_v1_region_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_region_v1_region_proto_goTypes,
		DependencyIndexes: file_region_v1_region_proto_depIdxs,
		EnumInfos:         file_region_v1_region_proto_enumTypes,
		MessageInfos:      file_region_v1_region_proto_msgTypes,
	}.Build()
	File_region_v1_region_proto = out.File
	file_region_v1_region_proto_goTypes = nil
	file_region_v1_region_proto_depIdxs = nil
}
