// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common_types/geo/geo.proto

package geo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_common_types_geo_geo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_geo_geo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_common_types_geo_geo_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Coordinate) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BottomLeft    *Coordinate            `protobuf:"bytes,1,opt,name=bottom_left,json=bottomLeft,proto3" json:"bottom_left,omitempty"`
	TopRight      *Coordinate            `protobuf:"bytes,2,opt,name=top_right,json=topRight,proto3" json:"top_right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_common_types_geo_geo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_geo_geo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_common_types_geo_geo_proto_rawDescGZIP(), []int{1}
}

func (x *BoundingBox) GetBottomLeft() *Coordinate {
	if x != nil {
		return x.BottomLeft
	}
	return nil
}

func (x *BoundingBox) GetTopRight() *Coordinate {
	if x != nil {
		return x.TopRight
	}
	return nil
}

type Polygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Coordinate          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	mi := &file_common_types_geo_geo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_geo_geo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_common_types_geo_geo_proto_rawDescGZIP(), []int{2}
}

func (x *Polygon) GetPoints() []*Coordinate {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_common_types_geo_geo_proto protoreflect.FileDescriptor

const file_common_types_geo_geo_proto_rawDesc = "" +
	"\n" +
	"\x1acommon_types/geo/geo.proto\x12\fcommon_types\"0\n" +
	"\n" +
	"Coordinate\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\"\x7f\n" +
	"\vBoundingBox\x129\n" +
	"\vbottom_left\x18\x01 \x01(\v2\x18.common_types.CoordinateR\n" +
	"bottomLeft\x125\n" +
	"\ttop_right\x18\x02 \x01(\v2\x18.common_types.CoordinateR\btopRight\";\n" +
	"\aPolygon\x120\n" +
	"\x06points\x18\x01 \x03(\v2\x18.common_types.CoordinateR\x06pointsB2Z0github.com/swayrider/protos/common_types/geo;geob\x06proto3"

var (
	file_common_types_geo_geo_proto_rawDescOnce sync.Once
	file_common_types_geo_geo_proto_rawDescData []byte
)

func file_common_types_geo_geo_proto_rawDescGZIP() []byte {
	file_common_types_geo_geo_proto_rawDescOnce.Do(func() {
		file_common_types_geo_geo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_geo_geo_proto_rawDesc), len(file_common_types_geo_geo_proto_rawDesc)))
	})
	return file_common_types_geo_geo_proto_rawDescData
}

var file_common_types_geo_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_types_geo_geo_proto_goTypes = []any{
	(*Coordinate)(nil),  // 0: common_types.Coordinate
	(*BoundingBox)(nil), // 1: common_types.BoundingBox
	(*Polygon)(nil),     // 2: common_types.Polygon
}
var file_common_types_geo_geo_proto_depIdxs = []int32{
	0, // 0: common_types.BoundingBox.bottom_left:type_name -> common_types.Coordinate
	0, // 1: common_types.BoundingBox.top_right:type_name -> common_types.Coordinate
	0, // 2: common_types.Polygon.points:type_name -> common_types.Coordinate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_types_geo_geo_proto_init() }
func file_common_types_geo_geo_proto_init() {
	if File_common_types_geo_geo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_geo_geo_proto_rawDesc), len(file_common_types_geo_geo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_geo_geo_proto_goTypes,
		DependencyIndexes: file_common_types_geo_geo_proto_depIdxs,
		MessageInfos:      file_common_types_geo_geo_proto_msgTypes,
	}.Build()
	File_common_types_geo_geo_proto = out.File
	file_common_types_geo_geo_proto_goTypes = nil
	file_common_types_geo_geo_proto_depIdxs = nil
}
