// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mail/v1/mail.proto

package mailv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string               `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,6,opt,name=htmlBody,proto3" json:"htmlBody,omitempty"`
	TextBody      string                 `protobuf:"bytes,7,opt,name=textBody,proto3" json:"textBody,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_mail_v1_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_v1_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_mail_v1_mail_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendRequest) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *SendRequest) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_mail_v1_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_v1_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_mail_v1_mail_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string               `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlTemplate  string                 `protobuf:"bytes,6,opt,name=html_template,json=htmlTemplate,proto3" json:"html_template,omitempty"`
	TextTemplate  string                 `protobuf:"bytes,7,opt,name=text_template,json=textTemplate,proto3" json:"text_template,omitempty"`
	Data          map[string]string      `protobuf:"bytes,8,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTemplateRequest) Reset() {
	*x = SendTemplateRequest{}
	mi := &file_mail_v1_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTemplateRequest) ProtoMessage() {}

func (x *SendTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_v1_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTemplateRequest.ProtoReflect.Descriptor instead.
func (*SendTemplateRequest) Descriptor() ([]byte, []int) {
	return file_mail_v1_mail_proto_rawDescGZIP(), []int{2}
}

func (x *SendTemplateRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendTemplateRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendTemplateRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendTemplateRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendTemplateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendTemplateRequest) GetHtmlTemplate() string {
	if x != nil {
		return x.HtmlTemplate
	}
	return ""
}

func (x *SendTemplateRequest) GetTextTemplate() string {
	if x != nil {
		return x.TextTemplate
	}
	return ""
}

func (x *SendTemplateRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTemplateResponse) Reset() {
	*x = SendTemplateResponse{}
	mi := &file_mail_v1_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTemplateResponse) ProtoMessage() {}

func (x *SendTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_v1_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTemplateResponse.ProtoReflect.Descriptor instead.
func (*SendTemplateResponse) Descriptor() ([]byte, []int) {
	return file_mail_v1_mail_proto_rawDescGZIP(), []int{3}
}

func (x *SendTemplateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mail_v1_mail_proto protoreflect.FileDescriptor

const file_mail_v1_mail_proto_rawDesc = "" +
	"\n" +
	"\x12mail/v1/mail.proto\x12\amail.v1\x1a\x1cgoogle/api/annotations.proto\"\xa5\x01\n" +
	"\vSendRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x03 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x04 \x03(\tR\x03bcc\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x1a\n" +
	"\bhtmlBody\x18\x06 \x01(\tR\bhtmlBody\x12\x1a\n" +
	"\btextBody\x18\a \x01(\tR\btextBody\"(\n" +
	"\fSendResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb4\x02\n" +
	"\x13SendTemplateRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x03 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x04 \x03(\tR\x03bcc\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12#\n" +
	"\rhtml_template\x18\x06 \x01(\tR\fhtmlTemplate\x12#\n" +
	"\rtext_template\x18\a \x01(\tR\ftextTemplate\x12:\n" +
	"\x04data\x18\b \x03(\v2&.mail.v1.SendTemplateRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x14SendTemplateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xbe\x03\n" +
	"\vMailService\x12Q\n" +
	"\x04Send\x12\x14.mail.v1.SendRequest\x1a\x15.mail.v1.SendResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/mail/send\x12b\n" +
	"\fSendInternal\x12\x14.mail.v1.SendRequest\x1a\x15.mail.v1.SendResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/mail/internal/send\x12r\n" +
	"\fSendTemplate\x12\x1c.mail.v1.SendTemplateRequest\x1a\x1d.mail.v1.SendTemplateResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/mail/send-template\x12\x83\x01\n" +
	"\x14SendTemplateInternal\x12\x1c.mail.v1.SendTemplateRequest\x1a\x1d.mail.v1.SendTemplateResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/mail/internal/send-templateB,Z*github.com/swayrider/protos/mail/v1;mailv1b\x06proto3"

var (
	file_mail_v1_mail_proto_rawDescOnce sync.Once
	file_mail_v1_mail_proto_rawDescData []byte
)

func file_mail_v1_mail_proto_rawDescGZIP() []byte {
	file_mail_v1_mail_proto_rawDescOnce.Do(func() {
		file_mail_v1_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mail_v1_mail_proto_rawDesc), len(file_mail_v1_mail_proto_rawDesc)))
	})
	return file_mail_v1_mail_proto_rawDescData
}

var file_mail_v1_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mail_v1_mail_proto_goTypes = []any{
	(*SendRequest)(nil),          // 0: mail.v1.SendRequest
	(*SendResponse)(nil),         // 1: mail.v1.SendResponse
	(*SendTemplateRequest)(nil),  // 2: mail.v1.SendTemplateRequest
	(*SendTemplateResponse)(nil), // 3: mail.v1.SendTemplateResponse
	nil,                          // 4: mail.v1.SendTemplateRequest.DataEntry
}
var file_mail_v1_mail_proto_depIdxs = []int32{
	4, // 0: mail.v1.SendTemplateRequest.data:type_name -> mail.v1.SendTemplateRequest.DataEntry
	0, // 1: mail.v1.MailService.Send:input_type -> mail.v1.SendRequest
	0, // 2: mail.v1.MailService.SendInternal:input_type -> mail.v1.SendRequest
	2, // 3: mail.v1.MailService.SendTemplate:input_type -> mail.v1.SendTemplateRequest
	2, // 4: mail.v1.MailService.SendTemplateInternal:input_type -> mail.v1.SendTemplateRequest
	1, // 5: mail.v1.MailService.Send:output_type -> mail.v1.SendResponse
	1, // 6: mail.v1.MailService.SendInternal:output_type -> mail.v1.SendResponse
	3, // 7: mail.v1.MailService.SendTemplate:output_type -> mail.v1.SendTemplateResponse
	3, // 8: mail.v1.MailService.SendTemplateInternal:output_type -> mail.v1.SendTemplateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mail_v1_mail_proto_init() }
func file_mail_v1_mail_proto_init() {
	if File_mail_v1_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mail_v1_mail_proto_rawDesc), len(file_mail_v1_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mail_v1_mail_proto_goTypes,
		DependencyIndexes: file_mail_v1_mail_proto_depIdxs,
		MessageInfos:      file_mail_v1_mail_proto_msgTypes,
	}.Build()
	File_mail_v1_mail_proto = out.File
	file_mail_v1_mail_proto_goTypes = nil
	file_mail_v1_mail_proto_depIdxs = nil
}
