// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: search/v1/search.proto

package searchv1

import (
	geo "github.com/swayrider/protos/common_types/geo"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Viewport      *geo.BoundingBox       `protobuf:"bytes,2,opt,name=viewport,proto3" json:"viewport,omitempty"`
	FocusPoint    *geo.Coordinate        `protobuf:"bytes,3,opt,name=focus_point,json=focusPoint,proto3,oneof" json:"focus_point,omitempty"`
	Size          *int32                 `protobuf:"varint,4,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Language      *string                `protobuf:"bytes,5,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchRequest) GetViewport() *geo.BoundingBox {
	if x != nil {
		return x.Viewport
	}
	return nil
}

func (x *SearchRequest) GetFocusPoint() *geo.Coordinate {
	if x != nil {
		return x.FocusPoint
	}
	return nil
}

func (x *SearchRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *SearchRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Result              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReverseGeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *geo.Coordinate        `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	Size          *int32                 `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Language      *string                `protobuf:"bytes,3,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseGeocodeRequest) Reset() {
	*x = ReverseGeocodeRequest{}
	mi := &file_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseGeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeRequest) ProtoMessage() {}

func (x *ReverseGeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeRequest.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *ReverseGeocodeRequest) GetPoint() *geo.Coordinate {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *ReverseGeocodeRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *ReverseGeocodeRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type ReverseGeocodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Result              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseGeocodeResponse) Reset() {
	*x = ReverseGeocodeResponse{}
	mi := &file_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseGeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeResponse) ProtoMessage() {}

func (x *ReverseGeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeResponse.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *ReverseGeocodeResponse) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Locality      string                 `protobuf:"bytes,2,opt,name=locality,proto3" json:"locality,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Layer         string                 `protobuf:"bytes,6,opt,name=layer,proto3" json:"layer,omitempty"`
	Lat           float64                `protobuf:"fixed64,7,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,8,opt,name=lon,proto3" json:"lon,omitempty"`
	Street        string                 `protobuf:"bytes,9,opt,name=street,proto3" json:"street,omitempty"`
	Housenumber   string                 `protobuf:"bytes,10,opt,name=housenumber,proto3" json:"housenumber,omitempty"`
	Id            string                 `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	Localadmin    string                 `protobuf:"bytes,12,opt,name=localadmin,proto3" json:"localadmin,omitempty"`
	CountryCode   string                 `protobuf:"bytes,13,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Name          string                 `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Result) GetLocality() string {
	if x != nil {
		return x.Locality
	}
	return ""
}

func (x *Result) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Result) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Result) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Result) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *Result) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Result) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Result) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Result) GetHousenumber() string {
	if x != nil {
		return x.Housenumber
	}
	return ""
}

func (x *Result) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Result) GetLocaladmin() string {
	if x != nil {
		return x.Localadmin
	}
	return ""
}

func (x *Result) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Result) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_search_v1_search_proto protoreflect.FileDescriptor

const file_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x16search/v1/search.proto\x12\tsearch.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1acommon_types/geo/geo.proto\"\xfa\x01\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x125\n" +
	"\bviewport\x18\x02 \x01(\v2\x19.common_types.BoundingBoxR\bviewport\x12>\n" +
	"\vfocus_point\x18\x03 \x01(\v2\x18.common_types.CoordinateH\x00R\n" +
	"focusPoint\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x04 \x01(\x05H\x01R\x04size\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x05 \x01(\tH\x02R\blanguage\x88\x01\x01B\x0e\n" +
	"\f_focus_pointB\a\n" +
	"\x05_sizeB\v\n" +
	"\t_language\"=\n" +
	"\x0eSearchResponse\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.search.v1.ResultR\aresults\"\x97\x01\n" +
	"\x15ReverseGeocodeRequest\x12.\n" +
	"\x05point\x18\x01 \x01(\v2\x18.common_types.CoordinateR\x05point\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x05H\x00R\x04size\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x03 \x01(\tH\x01R\blanguage\x88\x01\x01B\a\n" +
	"\x05_sizeB\v\n" +
	"\t_language\"E\n" +
	"\x16ReverseGeocodeResponse\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.search.v1.ResultR\aresults\"\xe7\x02\n" +
	"\x06Result\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1a\n" +
	"\blocality\x18\x02 \x01(\tR\blocality\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05layer\x18\x06 \x01(\tR\x05layer\x12\x10\n" +
	"\x03lat\x18\a \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\b \x01(\x01R\x03lon\x12\x16\n" +
	"\x06street\x18\t \x01(\tR\x06street\x12 \n" +
	"\vhousenumber\x18\n" +
	" \x01(\tR\vhousenumber\x12\x0e\n" +
	"\x02id\x18\v \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"localadmin\x18\f \x01(\tR\n" +
	"localadmin\x12!\n" +
	"\fcountry_code\x18\r \x01(\tR\vcountryCode\x12\x12\n" +
	"\x04name\x18\x0e \x01(\tR\x04name2\xea\x01\n" +
	"\rSearchService\x12_\n" +
	"\x06Search\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/search/search\x12x\n" +
	"\x0eReverseGeocode\x12 .search.v1.ReverseGeocodeRequest\x1a!.search.v1.ReverseGeocodeResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/search/reverseB0Z.github.com/swayrider/protos/search/v1;searchv1b\x06proto3"

var (
	file_search_v1_search_proto_rawDescOnce sync.Once
	file_search_v1_search_proto_rawDescData []byte
)

func file_search_v1_search_proto_rawDescGZIP() []byte {
	file_search_v1_search_proto_rawDescOnce.Do(func() {
		file_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)))
	})
	return file_search_v1_search_proto_rawDescData
}

var file_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_search_v1_search_proto_goTypes = []any{
	(*SearchRequest)(nil),          // 0: search.v1.SearchRequest
	(*SearchResponse)(nil),         // 1: search.v1.SearchResponse
	(*ReverseGeocodeRequest)(nil),  // 2: search.v1.ReverseGeocodeRequest
	(*ReverseGeocodeResponse)(nil), // 3: search.v1.ReverseGeocodeResponse
	(*Result)(nil),                 // 4: search.v1.Result
	(*geo.BoundingBox)(nil),        // 5: common_types.BoundingBox
	(*geo.Coordinate)(nil),         // 6: common_types.Coordinate
}
var file_search_v1_search_proto_depIdxs = []int32{
	5, // 0: search.v1.SearchRequest.viewport:type_name -> common_types.BoundingBox
	6, // 1: search.v1.SearchRequest.focus_point:type_name -> common_types.Coordinate
	4, // 2: search.v1.SearchResponse.results:type_name -> search.v1.Result
	6, // 3: search.v1.ReverseGeocodeRequest.point:type_name -> common_types.Coordinate
	4, // 4: search.v1.ReverseGeocodeResponse.results:type_name -> search.v1.Result
	0, // 5: search.v1.SearchService.Search:input_type -> search.v1.SearchRequest
	2, // 6: search.v1.SearchService.ReverseGeocode:input_type -> search.v1.ReverseGeocodeRequest
	1, // 7: search.v1.SearchService.Search:output_type -> search.v1.SearchResponse
	3, // 8: search.v1.SearchService.ReverseGeocode:output_type -> search.v1.ReverseGeocodeResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_search_v1_search_proto_init() }
func file_search_v1_search_proto_init() {
	if File_search_v1_search_proto != nil {
		return
	}
	file_search_v1_search_proto_msgTypes[0].OneofWrappers = []any{}
	file_search_v1_search_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_search_proto_goTypes,
		DependencyIndexes: file_search_v1_search_proto_depIdxs,
		MessageInfos:      file_search_v1_search_proto_msgTypes,
	}.Build()
	File_search_v1_search_proto = out.File
	file_search_v1_search_proto_goTypes = nil
	file_search_v1_search_proto_depIdxs = nil
}
