// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: health/v1/health.proto

package healthv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_ServiceStatus int32

const (
	HealthResponse_UNKNOWN HealthResponse_ServiceStatus = 0 // Unknown component
	HealthResponse_UP      HealthResponse_ServiceStatus = 1 // Up and running
	HealthResponse_DOWN    HealthResponse_ServiceStatus = 2 // Not running
)

// Enum value maps for HealthResponse_ServiceStatus.
var (
	HealthResponse_ServiceStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "UP",
		2: "DOWN",
	}
	HealthResponse_ServiceStatus_value = map[string]int32{
		"UNKNOWN": 0,
		"UP":      1,
		"DOWN":    2,
	}
)

func (x HealthResponse_ServiceStatus) Enum() *HealthResponse_ServiceStatus {
	p := new(HealthResponse_ServiceStatus)
	*p = x
	return p
}

func (x HealthResponse_ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_health_v1_health_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_ServiceStatus) Type() protoreflect.EnumType {
	return &file_health_v1_health_proto_enumTypes[0]
}

func (x HealthResponse_ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_ServiceStatus.Descriptor instead.
func (HealthResponse_ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_health_v1_health_proto_rawDescGZIP(), []int{3, 0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_health_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_health_v1_health_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_health_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_health_v1_health_proto_rawDescGZIP(), []int{1}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"` // Welke componen ("" voor gehele service)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_health_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_health_v1_health_proto_rawDescGZIP(), []int{2}
}

func (x *HealthRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        HealthResponse_ServiceStatus `protobuf:"varint,1,opt,name=status,proto3,enum=health.v1.HealthResponse_ServiceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_health_v1_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_health_v1_health_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() HealthResponse_ServiceStatus {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

var File_health_v1_health_proto protoreflect.FileDescriptor

const file_health_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x16health/v1/health.proto\x12\thealth.v1\x1a\x1cgoogle/api/annotations.proto\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"-\n" +
	"\rHealthRequest\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\"\x81\x01\n" +
	"\x0eHealthResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.health.v1.HealthResponse.ServiceStatusR\x06status\".\n" +
	"\rServiceStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02UP\x10\x01\x12\b\n" +
	"\x04DOWN\x10\x022\xbb\x01\n" +
	"\rHealthService\x12T\n" +
	"\x04Ping\x12\x16.health.v1.PingRequest\x1a\x17.health.v1.PingResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/health/ping\x12T\n" +
	"\x05Check\x12\x18.health.v1.HealthRequest\x1a\x19.health.v1.HealthResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/healthB0Z.github.com/swayrider/protos/health/v1;healthv1b\x06proto3"

var (
	file_health_v1_health_proto_rawDescOnce sync.Once
	file_health_v1_health_proto_rawDescData []byte
)

func file_health_v1_health_proto_rawDescGZIP() []byte {
	file_health_v1_health_proto_rawDescOnce.Do(func() {
		file_health_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_v1_health_proto_rawDesc), len(file_health_v1_health_proto_rawDesc)))
	})
	return file_health_v1_health_proto_rawDescData
}

var file_health_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_health_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_health_v1_health_proto_goTypes = []any{
	(HealthResponse_ServiceStatus)(0), // 0: health.v1.HealthResponse.ServiceStatus
	(*PingRequest)(nil),               // 1: health.v1.PingRequest
	(*PingResponse)(nil),              // 2: health.v1.PingResponse
	(*HealthRequest)(nil),             // 3: health.v1.HealthRequest
	(*HealthResponse)(nil),            // 4: health.v1.HealthResponse
}
var file_health_v1_health_proto_depIdxs = []int32{
	0, // 0: health.v1.HealthResponse.status:type_name -> health.v1.HealthResponse.ServiceStatus
	1, // 1: health.v1.HealthService.Ping:input_type -> health.v1.PingRequest
	3, // 2: health.v1.HealthService.Check:input_type -> health.v1.HealthRequest
	2, // 3: health.v1.HealthService.Ping:output_type -> health.v1.PingResponse
	4, // 4: health.v1.HealthService.Check:output_type -> health.v1.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_health_v1_health_proto_init() }
func file_health_v1_health_proto_init() {
	if File_health_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_v1_health_proto_rawDesc), len(file_health_v1_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_v1_health_proto_goTypes,
		DependencyIndexes: file_health_v1_health_proto_depIdxs,
		EnumInfos:         file_health_v1_health_proto_enumTypes,
		MessageInfos:      file_health_v1_health_proto_msgTypes,
	}.Build()
	File_health_v1_health_proto = out.File
	file_health_v1_health_proto_goTypes = nil
	file_health_v1_health_proto_depIdxs = nil
}
